/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TorrentsRouteImport } from './routes/torrents'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TorrentsIndexRouteImport } from './routes/torrents.index'
import { Route as SetupIndexRouteImport } from './routes/setup.index'
import { Route as TorrentsTorrentRouteImport } from './routes/torrents.$torrent'

const TorrentsRoute = TorrentsRouteImport.update({
  id: '/torrents',
  path: '/torrents',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TorrentsIndexRoute = TorrentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TorrentsRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRoute,
} as any)
const TorrentsTorrentRoute = TorrentsTorrentRouteImport.update({
  id: '/$torrent',
  path: '/$torrent',
  getParentRoute: () => TorrentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/torrents': typeof TorrentsRouteWithChildren
  '/torrents/$torrent': typeof TorrentsTorrentRoute
  '/setup/': typeof SetupIndexRoute
  '/torrents/': typeof TorrentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/torrents/$torrent': typeof TorrentsTorrentRoute
  '/setup': typeof SetupIndexRoute
  '/torrents': typeof TorrentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRouteWithChildren
  '/torrents': typeof TorrentsRouteWithChildren
  '/torrents/$torrent': typeof TorrentsTorrentRoute
  '/setup/': typeof SetupIndexRoute
  '/torrents/': typeof TorrentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/torrents'
    | '/torrents/$torrent'
    | '/setup/'
    | '/torrents/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/torrents/$torrent'
    | '/setup'
    | '/torrents'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/torrents'
    | '/torrents/$torrent'
    | '/setup/'
    | '/torrents/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRouteWithChildren
  TorrentsRoute: typeof TorrentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/torrents': {
      id: '/torrents'
      path: '/torrents'
      fullPath: '/torrents'
      preLoaderRoute: typeof TorrentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torrents/': {
      id: '/torrents/'
      path: '/'
      fullPath: '/torrents/'
      preLoaderRoute: typeof TorrentsIndexRouteImport
      parentRoute: typeof TorrentsRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRoute
    }
    '/torrents/$torrent': {
      id: '/torrents/$torrent'
      path: '/$torrent'
      fullPath: '/torrents/$torrent'
      preLoaderRoute: typeof TorrentsTorrentRouteImport
      parentRoute: typeof TorrentsRoute
    }
  }
}

interface SetupRouteChildren {
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteChildren: SetupRouteChildren = {
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteWithChildren = SetupRoute._addFileChildren(SetupRouteChildren)

interface TorrentsRouteChildren {
  TorrentsTorrentRoute: typeof TorrentsTorrentRoute
  TorrentsIndexRoute: typeof TorrentsIndexRoute
}

const TorrentsRouteChildren: TorrentsRouteChildren = {
  TorrentsTorrentRoute: TorrentsTorrentRoute,
  TorrentsIndexRoute: TorrentsIndexRoute,
}

const TorrentsRouteWithChildren = TorrentsRoute._addFileChildren(
  TorrentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRouteWithChildren,
  TorrentsRoute: TorrentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
