import Link from "next/link";
import { CodeBlock } from "./code-block";
import { Reveal, SectionRule } from "./motion";

const SCAFFOLD_CMD = `bunx create-minato-scraper@latest my-scraper`;

const SCRAPER_CODE = `// src/index.ts — generated by create-minato-scraper
import { defineScraper } from "@minato/skit";

export default defineScraper({
  name: "my-scraper",
  schedule: "every 6 hours",
  async run({ ingest }) {
    // fetch, parse, and lock down records
  },
});`;

export function SdkSection() {
	return (
		<section className="border-t border-web-line py-24 md:py-32">
			<div className="mx-auto max-w-5xl px-6">
				<SectionRule label="04 / Build" />

				<div className="grid grid-cols-1 gap-10 md:grid-cols-[2fr_3fr] md:gap-16">
					{/* Prose */}
					<Reveal className="flex flex-col justify-center">
						<h2
							className="mb-6 font-display font-bold leading-none tracking-tight text-web-fg"
							style={{ fontSize: "clamp(1.8rem, 3.5vw, 2.8rem)" }}
						>
							Write a scraper
							<br />
							in minutes.
							<br />
							<span className="text-web-muted">Ship it to anyone.</span>
						</h2>
						<p className="mb-5 text-sm leading-relaxed text-web-muted">
							Community scrapers are plain TypeScript modules built with{" "}
							<code className="rounded bg-web-elevated px-1.5 py-0.5 font-mono text-xs text-web-fg">
								@minato/skit
							</code>
							. Scaffold one in seconds with{" "}
							<code className="rounded bg-web-elevated px-1.5 py-0.5 font-mono text-xs text-web-fg">
								create-minato-scraper
							</code>
							, install from the registry, or paste a GitHub repo URL directly
							from the dashboard. Minato pulls and mounts it automatically.
						</p>
						<p className="mb-8 text-sm leading-relaxed text-web-muted">
							For heavier workloads, sidecar scrapers run as isolated containers
							and connect over the network. Resource-intensive sources stay off
							the main stack entirely.
						</p>
						<div className="flex flex-col gap-2.5">
							<Link
								href="/docs/scrapers"
								className="group inline-flex items-center gap-1 text-sm text-web-muted/60 transition-colors hover:text-web-fg"
							>
								<span className="underline decoration-web-muted/30 underline-offset-4">
									@minato/skit SDK reference
								</span>
								<span className="transition-transform group-hover:translate-x-0.5">
									→
								</span>
							</Link>
							<Link
								href="/docs/scrapers"
								className="group inline-flex items-center gap-1 text-sm text-web-muted/60 transition-colors hover:text-web-fg"
							>
								<span className="underline decoration-web-muted/30 underline-offset-4">
									Building your first scraper
								</span>
								<span className="transition-transform group-hover:translate-x-0.5">
									→
								</span>
							</Link>
						</div>
					</Reveal>

					{/* Code blocks */}
					<Reveal className="flex flex-col gap-3" delay={0.12}>
						<CodeBlock language="bash" code={SCAFFOLD_CMD} />
						<CodeBlock
							language="typescript"
							filename="src/index.ts"
							code={SCRAPER_CODE}
						/>
					</Reveal>
				</div>
			</div>
		</section>
	);
}
