import { useMutation } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { format } from "date-fns";
import { Fingerprint, Loader2, Trash2 } from "lucide-react";
import { toast } from "sonner";

import { PageHeader } from "@/components/admin/page-header";
import { Button } from "@/components/ui/button";
import { authClient } from "@/lib/auth-client";

export const Route = createFileRoute("/dashboard/security")({
	component: SecurityPage,
});

function Section({
	title,
	description,
	action,
	children,
}: {
	title: string;
	description?: string;
	action?: React.ReactNode;
	children: React.ReactNode;
}) {
	return (
		<section className="rounded-xl border border-border/60 bg-card">
			<div className="flex items-center justify-between border-border border-b px-5 py-4">
				<div>
					<h2 className="font-semibold text-foreground text-sm">{title}</h2>
					{description && (
						<p className="mt-0.5 text-muted-foreground text-xs">{description}</p>
					)}
				</div>
				{action}
			</div>
			<div className="divide-y divide-border">{children}</div>
		</section>
	);
}

function SecurityPage() {
	// useListPasskeys is a React hook auto-generated by better-auth from the listPasskeys atom
	// The atomListeners in the passkey plugin automatically invalidate this after add/delete
	const { data: passkeys, isPending } = authClient.useListPasskeys();

	const addPasskeyMutation = useMutation({
		mutationFn: () => authClient.passkey.addPasskey(),
		onSuccess: () => {
			toast.success("Passkey registered");
		},
		onError: (err) => {
			toast.error(err instanceof Error ? err.message : "Failed to register passkey");
		},
	});

	const deletePasskeyMutation = useMutation({
		mutationFn: (id: string) =>
			authClient.passkey.deletePasskey({ id }),
		onSuccess: () => {
			toast.success("Passkey removed");
		},
		onError: (err) => {
			toast.error(err instanceof Error ? err.message : "Failed to remove passkey");
		},
	});

	return (
		<div>
			<PageHeader
				eyebrow="dashboard // security"
				title="Security"
				description="Manage passkeys for passwordless sign-in."
			/>

			<div className="space-y-6">
				<Section
					title="Passkeys"
					description="Sign in with Face ID, Touch ID, or a security key — no password needed."
					action={
						<Button
							size="sm"
							variant="outline"
							onClick={() => addPasskeyMutation.mutate()}
							disabled={addPasskeyMutation.isPending}
							className="gap-1.5"
						>
							{addPasskeyMutation.isPending ? (
								<Loader2 className="size-3.5 animate-spin" />
							) : (
								<Fingerprint className="size-3.5" />
							)}
							Add passkey
						</Button>
					}
				>
					{isPending ? (
						<div className="flex items-center justify-center py-8">
							<Loader2 className="size-4 animate-spin text-muted-foreground" />
						</div>
					) : !passkeys || passkeys.length === 0 ? (
						<div className="flex flex-col items-center gap-2 px-5 py-10 text-center">
							<Fingerprint className="size-8 text-muted-foreground/40" />
							<p className="text-muted-foreground text-sm">No passkeys registered</p>
							<p className="text-muted-foreground text-xs">
								Add a passkey to sign in without a password.
							</p>
						</div>
					) : (
						passkeys.map((pk) => (
							<div
								key={pk.id}
								className="flex items-center justify-between px-5 py-3.5"
							>
								<div className="flex items-center gap-3">
									<Fingerprint className="size-4 shrink-0 text-muted-foreground/60" />
									<div>
										<p className="text-foreground text-sm">
											{pk.deviceType === "singleDevice"
												? "Device-bound passkey"
												: "Synced passkey"}
										</p>
										<p className="text-muted-foreground text-xs">
											Added {format(new Date(pk.createdAt), "PPP")}
										</p>
									</div>
								</div>
								<Button
									variant="ghost"
									size="icon"
									className="size-8 text-muted-foreground hover:text-destructive"
									onClick={() => deletePasskeyMutation.mutate(pk.id)}
									disabled={deletePasskeyMutation.isPending}
								>
									<Trash2 className="size-3.5" />
									<span className="sr-only">Remove passkey</span>
								</Button>
							</div>
						))
					)}
				</Section>
			</div>
		</div>
	);
}
